apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ncroperations.ncr.netease.com
spec:
  conversion:
    strategy: None
  group: ncr.netease.com
  names:
    kind: NcrOperation
    listKind: NcrOperationList
    plural: ncroperations
    shortNames:
    - ncropt
    singular: ncroperation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NcrOperation is the control script's spec
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              args:
                additionalProperties:
                  type: string
                type: object
              command:
                enum:
                - restart
                - rebuild
                - rollbackconfigmap
                - rebalance
                - update
                - rdbrecover
                - masterbalance
                type: string
              cron:
                type: string
              retryPolicy:
                type: string
              retryThreshold:
                type: integer
            required:
            - args
            - command
            type: object
            
        type: object
        
    served: true
    storage: true
    subresources:
